#!/usr/bin/env bash
# to run on my server, using code that interacts
# with the supervisor here
# https://github.com/seanbreckenridge/vps
# to update and restart the server once a day

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "$THIS_DIR" || exit $?

git stash
git stash drop
git pull

logtime() {
	local dt
	dt="$(date)"
	echo "${dt}"
	echo "${dt}" >&2
}

set -e

while true; do
	logtime
	PROJECTS_BG_UPDATE=1 ./update
	yarn prod-build
	super --ctl restart projects
	sleep 12h
done
