#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

commit() {
	if [[ -n "$1" ]]; then
		git commit -m "$*"
		return $?
	else
		git commit -m "periodic update"
		return $?
	fi
}

sync_images() {
	s4cmd dsync ./public s3://sean-fish-imageproxy/project-images
}

./update &&
	git add . &&
	commit "$@" &&
	git push &&
	ssh vultr
