#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

commit() {
	if [[ -n "$1" ]]; then
		git commit -m "$*"
		return $?
	else
		git commit -m "periodic update"
		return $?
	fi
}

sync_images() {
	s4cmd dsync ./public s3://sean-fish-imageproxy/project-images
}

deploy() {
	ssh vultr 'cd ~/code/projects && PATH="${HOME}/vps:$PATH" ONCE=1 bash -x ./bg_update'
}

while getopts ':hds' opt; do
	case "$opt" in
	d)
		deploy
		exit 0
		;;
	s)
		sync_images
		exit 0
		;;
	*)
		echo "Usage: ./push [-ds] [commit message]"
		exit 1
		;;
	esac
done

./update &&
	yarn lint &&
	yarn build &&
	sync_images &&
	git add . &&
	commit "$@" &&
	git push &&
	deploy
